from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

# Canonical risk vocabulary shared by backend + frontend.
RiskLevel = Literal["safe", "suspicious", "danger"]


class ScanRequest(BaseModel):
    # Request shape accepted by API clients (frontend, tests, integrations).
    url: str = Field(min_length=1, description="URL extracted from scanned QR code.")
    qr_code_id: str | None = Field(
        default=None,
        description="Protected QR identifier if generated by QRoulette business flow.",
    )


class RiskAnalysis(BaseModel):
    # Normalized risk signals returned by analysis pipeline.
    risk_score: int = Field(ge=0, le=100)
    risk_level: RiskLevel
    flagged_safe_browsing: bool
    flagged_threat_intel: bool
    typosquatting_detected: bool
    domain_age_days: int | None = None
    redirect_hops: int = 0
    ssl_valid: bool
    ai_summary: str


class ScanDecisionResponse(BaseModel):
    # Final allow/block decision contract consumed by UI.
    allowed: bool
    destination: str
    reason: str
    analysis: RiskAnalysis


class DashboardSummaryResponse(BaseModel):
    # Compact counters for dashboard overview cards/charts.
    safe: int = 0
    suspicious: int = 0
    danger: int = 0
    total: int = 0


class ScanRecord(BaseModel):
    # Mirrors the `scans` table columns used in dashboard recent feed.
    id: str
    created_at: datetime
    scanned_url: str
    qr_code_id: str | None = None
    risk_score: int | None = None
    risk_level: RiskLevel | None = None
    flagged_safe_browsing: bool = False
    flagged_threat_intel: bool = False
    typosquatting_detected: bool = False
    domain_age_days: int | None = None
    redirect_hops: int | None = None
    ssl_valid: bool | None = None
    ai_summary: str | None = None
    ip_address: str | None = None
    user_agent: str | None = None
    country: str | None = None
